### ISSUE TITLE
정의할 것

### ISSUE THREAD

**Issue by webhacking** [JangandWoo/flag#1]
- 타입
  - Info (default)
  - Success
  - Warning
  - Error
- 포지션
  - 중앙 (기본)
  - 우측 상단
  - 좌측 상단
  - 우측 하단
  - 좌측 하단
- 인자
  - 메세지(필수),제목,사이즈

논의한 것 :  돔 구조 간결, 속도, IE7까지 support

**Comment by humit0** [comment]
사이즈는 small, middle, big 정도로만 해서 좀 더 간편하게 사이즈 조절.

**Comment by webhacking** [comment]
사이즈 정의 된 것
- small (*150px)
- middle (*300px)
- big (*450px)

모바일은 미디어쿼리이용해서 정의할 것.

**Comment by webhacking** [comment]
XMLHttpRequest 핸들링 추가
